services:
  notes-mysql:
    image: mysql:8.0
    container_name: notes-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: notesdb
      MYSQL_USER: notesuser
      MYSQL_PASSWORD: notespass
    ports:
      - "3308:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  notes-app:
    build: .
    container_name: notes-app
    restart: always
    ports:
      - "8081:8080"
    depends_on:
      - notes-mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://notes-mysql:3306/notesdb
      SPRING_DATASOURCE_USERNAME: notesuser
      SPRING_DATASOURCE_PASSWORD: notespass

  jenkins:
    build:
      context: .
      dockerfile: Dockerfile-jenkins
    container_name: jenkins-master
    restart: always
    privileged: true          # quan trọng để Jenkins chạy Docker
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins-data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock   # Docker-in-Docker
    networks:
      - jenkins-net


volumes:
  mysql_data:
  jenkins-data:

networks:
  jenkins-net:
