# Dockerfile-agent
FROM openjdk:21-jdk-slim

# Chuyển sang root để cài đặt
USER root

# Cài curl để tải agent.jar
RUN apt-get update && apt-get install -y curl && rm -rf /var/lib/apt/lists/*

# Tạo user jenkins và thư mục agent
RUN groupadd -r jenkins && useradd -m -r -g jenkins -d /home/jenkins jenkins
RUN mkdir -p /home/jenkins/agent \
    && chown -R jenkins:jenkins /home/jenkins \
    && chmod 755 /home/jenkins/agent

# Copy entrypoint script
COPY entrypoint.sh /home/jenkins/agent/entrypoint.sh

# Chỉnh quyền cho entrypoint
RUN chmod +x /home/jenkins/agent/entrypoint.sh \
    && chown jenkins:jenkins /home/jenkins/agent/entrypoint.sh

# Chuyển về user jenkins
USER jenkins

WORKDIR /home/jenkins/agent

ENTRYPOINT ["./entrypoint.sh"]
