services:
  notes-mysql:
    image: mysql:8.0
    container_name: notes-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: notesdb
      MYSQL_USER: notesuser
      MYSQL_PASSWORD: notespass
    ports:
      - "3308:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  notes-app:
    build: .
    container_name: notes-app
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - notes-mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://notes-mysql:3306/notesdb
      SPRING_DATASOURCE_USERNAME: notesuser
      SPRING_DATASOURCE_PASSWORD: notespass

  jenkins-docker:
    image: docker:dind
    container_name: jenkins-docker
    privileged: true
    restart: always
    networks:
      - jenkins-net
    environment:
      DOCKER_TLS_CERTDIR: /certs
    volumes:
      - jenkins-docker-certs:/certs/client
      - jenkins-data:/var/jenkins_home
    ports:
      - "2376:2376"

  jenkins:
    build:
      context: .
      dockerfile: Dockerfile-jenkins
    container_name: jenkins-blueocean
    restart: on-failure
    networks:
      - jenkins-net
    depends_on:
      - jenkins-docker
    environment:
      DOCKER_HOST: tcp://jenkins-docker:2376
      DOCKER_CERT_PATH: /certs/client
      DOCKER_TLS_VERIFY: 1
    ports:
      - "8081:8080"
      - "50000:50000"
    volumes:
      - jenkins-data:/var/jenkins_home
      - jenkins-docker-certs:/certs/client:ro

volumes:
  mysql_data:
  jenkins-data:
  jenkins-docker-certs:

networks:
  jenkins-net:
